### ISSUE TITLE
av_interleaved_write_frame(): Broken pipe

### ISSUE THREAD

**Issue by na018** [facebookresearch/VideoPose3D#108]
First, thanks for your awesome work :clap: 

However, I can't get the inference working. 
In *Step 3* of the tutorial I get the following error:

(however I converted the video already)
- output from ffmpeg -i 
```
    Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:12.16, start: 0.020000, bitrate: 15332 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720, 15330 kb/s, 50 fps, 50 tbr, 12800 tbn, 100 tbc (default)
    Metadata:
      handler_name    : VideoHandler
```
- Step 3 error output
```bash
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/videos/biellmann2.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:12.16, start: 0.020000, bitrate: 4431 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720, 4429 kb/s, 50 fps, 50 tbr, 12800 tbn, 100 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
    Stream #0:0(und): Video: rawvideo (BGR[24] / 0x18524742), bgr24, 1280x720, q=2-31, 200 kb/s, 50 fps, 50 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc56.60.100 rawvideo
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
INFO infer_video.py:  71: Frame 0
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at conv_op_cudnn.cc:572] status == CUDNN_STATUS_SUCCESS. 8 vs 0. , Error at: /var/lib/jenkins/workspace/caffe2/operators/conv_op_cudnn.cc:572: CUDNN_STATUS_EXECUTION_FAILED Error from operator:
input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
*** Aborted at 1576048858 (unix time) try "date -d @1576048858" if you are using GNU date ***
PC: @     0x7f5f753fa428 gsignal
*** SIGABRT (@0xb86) received by PID 2950 (TID 0x7f5e5effd700) from PID 2950; stack trace: ***
    @     0x7f5f757a0390 (unknown)
    @     0x7f5f753fa428 gsignal
    @     0x7f5f753fc02a abort
    @     0x7f5f6edbb84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f5f6edb96b6 (unknown)
    @     0x7f5f6edb9701 std::terminate()
    @     0x7f5f6ede4d38 (unknown)
    @     0x7f5f757966ba start_thread
    @     0x7f5f754cc41d clone
    @                0x0 (unknown)
av_interleaved_write_frame(): Broken pipe
frame=    2 fps=1.3 q=-0.0 Lsize=    5400kB time=00:00:00.04 bitrate=1105920.0kbits/s
video:5400kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
Conversion failed!
Aborted (core dumped)
```
Any ideas what I'm doing wrong :thinking: ?

**Comment by dariopavllo** [comment]
It seems to be something related to your Caffe2 build / CUDA library. I would expect to see the same error with the Detectron demo.

What's your GPU, and what CUDA version are you running?
I found a similar issue here: https://github.com/facebookresearch/Detectron/issues/807

**Comment by na018** [comment]
You're right. I tried to use the detectron docker container. Since all tests passed I assumed everything did work. When I try to execute the demo from detectron I run into the same error. 
Since [#807](https://github.com/facebookresearch/Detectron/issues/807) with a RTX graphic card met the same issues, I probably should continue to search for a solution there.

Somehow all my attempt to rewrite the dockerfile failed...
Hopefully I get it working soon.

Thank you :)

**Comment by na018** [comment]
Finally was able to create a Dockerfile and commented this in  [#807](https://github.com/facebookresearch/Detectron/issues/807).

Additionally, I extended the Dockerfile to work for VideoPose3D and created a Pull Request: [facebookresearch/VideoPose3D/pull/109](https://github.com/facebookresearch/VideoPose3D/pull/109)
:tada:

**Comment by MohamedKari** [comment]
Solved it by switching from a Tesla T4 to a Tesla K80.
