### ISSUE TITLE
Why this code not utilizing GPU when running it on window?

### ISSUE THREAD

**Issue by sajjadafridi** [facebookresearch/VideoPose3D#120]
I check this code on both window and Ubuntu OS. What i found is that in Ubuntu it work well and utilize GPU but when executing it on the window it does not? I also created an issue in one of the fork of this code @https://github.com/zh-plus/video-to-pose3D/issues but still no help. 
Any help will be appreciated in this regard?

**Comment by dariopavllo** [comment]
I remember testing it on Windows and it worked fine.

Are you sure you installed PyTorch correctly (with GPU support)? Internally our code calls `torch.cuda.is_available()`. What does it return in your case? (print it inside the script, maybe some environment variable is wrongly set)

Do you have the same problem with other PyTorch scripts?

**Comment by sajjadafridi** [comment]
> I remember testing it on Windows and it worked fine.
> 
> Are you sure you installed PyTorch correctly (with GPU support)? Internally our code calls `torch.cuda.is_available()`. What does it return in your case? (print it inside the script, maybe some environment variable is wrongly set)
> 
> Do you have the same problem with other PyTorch scripts?

i tried it and it return **true**.

**Comment by xiao19971225** [comment]
hello,
Have you solved this problem? I encountered the same problem.

**Comment by sajjadafridi** [comment]
yes i did it.

Regard

[image: photo]
Muhammad Sajjad
Research Officer at  Al-Khawarzmi Institute of Computer Science
A  UET GT Road, Lahore
P +92 42 99 029450   <+92+42+99+029450> M +92 3005946554   <+92+3005946554>
E muhammad.sajjad@kics.edu.pk  <muhammad.sajjad@kics.edu.pk>
W http://www.kics.edu.pk/staff/sajad_khan_afridi
Skype sajjad.afridi58 <https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/sajjuafi>
<http://www.linkedin.com/in/sajjad-afridi-4a3662a1>
<http://twitter.com/Crack_Afridi>
